### ISSUE TITLE
Comments-testing

### ISSUE THREAD

**Issue by duarHydro** [duarHydro/actions-learning-pathway#2]
## This issue will be use for practice.

Add comments with code, image o text.

**Comment by duarHydro** [comment]
### Print the log of the first test.

![Captura de pantalla 2024-04-26 102929](https://github.com/duarHydro/actions-learning-pathway/assets/158470007/e18fcfe4-2a03-42f6-92c3-35160ae51501)

```
> name: hello-world
> on: push
> jobs: 
>   hello-world-job:
>     runs-on: ubuntu-latest
>     steps: 
>       - name: Check out repository code
>         uses: actions/checkout@v3
>       - run: echo "$(cat hello_world.txt)"
```

**Comment by jbermejo-ied** [comment]
Maybe you can take a look at this? https://www.runatlantis.io/
